#!/usr/bin/env ruby

git_bundles = [
	"git://github.com/othree/html5-syntax.vim.git",
	"git://github.com/scrooloose/syntastic.git",
	"git://github.com/scrooloose/nerdtree.git",
	"git://github.com/altercation/vim-colors-solarized.git",
	"git://github.com/tpope/vim-pathogen.git",
	"git://github.com/tpope/vim-fugitive.git",
	"git://github.com/ervandew/supertab.git",
	"git://github.com/pangloss/vim-javascript.git",
]

vim_org_scripts = [
	["IndexedSearch", "7062", "plugin"],
	["jquery", "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Dumping current bundles..."
Dir["*"].each {|d| FileUtils.rm_rf d}

puts "Grabbing bundles from git"
git_bundles.each do |url|
	dir = url.split('/').last.sub(/\.git$/, '')
	puts "unpacking #{url} into #{dir}"
	`git clone #{url} #{dir}`
	# FileUtils.rm_rf(File.join(dir, ".git"))
end

puts "Grabbing vim.org scripts"
vim_org_scripts.each do |name, script_id, script_type|
	puts "downloading #{name}"
	local_file = File.join(name, script_type, "#{name}.vim")
	FileUtils.mkdir_p(File.dirname(local_file))
	File.open(local_file, "w") do |file|
		file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
	end
end

puts "Complete!"

